steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/lexdigitalhd', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/lexdigitalhd']

- name: 'gcr.io/google-cloud-sdk'
  args: ['gcloud', 'run', 'deploy', 'lexdigitalhd',
         '--image', 'gcr.io/$PROJECT_ID/lexdigitalhd',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated']
